#!/usr/bin/env node
const colors = require('colors');
const cmd = require('commander');

cmd
  .command('todo')
  .description('Todo list for this challenge')
  .action(function(){
    console.log('Tareas a realizar:'.green.bold);
    console.log('* Agregar un comando'.white, '\'help\''.blue.bold, 'para mostrar la lista de comandos disponibles'.white);
    console.log('* Agregar un comando'.white, '\'git\''.blue.bold, 'que liste los pasos a seguir para hacer un commit'.white);
    console.log('* Agregar un comando'.white, '\'linux\''.blue.bold, 'que muestre un link a los pasos a seguir para configurar linux en su máquina'.white);
    console.log('* Agregar un comando'.white, '\'clases\''.blue.bold, 'que muestre los horarios de clase de coderoom'.white);
  });

cmd
 .command('help')
 .description('Comando de ayuda :D')
 .action(function(){
   console.log('¿Problemas? Aquí una lista de comandos útiles'.red.bold);
   console.log('Pasos para hacer un commit exitoso: '.white.bold, './coderoom git'.white);
   console.log('¿Quieres cambiar a Elementary OS?'.white.bold, './coderoom linux'.white);
   console.log('Horario de las clases (por si no te lo sabías)'.white.bold, './coderoom horarios'.white);
 })

cmd
 .command('git')
 .description('Para dejar un comentario en tus repositorios')
 .action(function(){
   console.log('¿Como comentar mis cambios?'.green.bold);
   console.log('Entra a tu carpeta en tu terminal con:'.white, 'cd dirección.aquí'.blue);
   console.log('Inicia git en ésa carpeta con:'.white, 'git init'.blue);
   console.log('Añade los archivos creados con:'.white, 'git add .'.blue);
   console.log('Y escribes'.white, 'git commit -m "'.blue);
   console.log('Recuerda que tu comentario debe ir entre las comillas'.white, 'git commit -m "aquí va el comentario" '.blue);
 })

cmd
 .command('horarios')
 .description('Los días y horarios de las clases')
 .action(function(){
   console.log('Horarios de '.green,'C'.white.bold,'O'.white.bold,'D'.white.bold,'E'.white.bold,'R'.gray.bold,'['.yellow.bold,']'.yellow.bold,'M'.gray.bold);
   console.log('Lunes   Miercoles  Sabados'.white);
   console.log('18:00   18:00      09:00'.white);
   console.log('  a       a          a'.white);
   console.log('20:00   21:00      13:00'.white);  
 })

cmd
 .command('linux')
 .description('Cómo instalar linux')
 .action(function(){
   console.log('Como instalar Elementary OS (distribución de linux)'.green.bold)
   console.log('Puedes consultar TODOS los pasos aqui: '.white, href='https://elementary.io/es/docs/installation'.blue);
 })

cmd
 .command('costo')
 .description('Calcular el salario x hora')
 .action(function(){
   var costo = this.cmd.command;
   console.log('Costo por hora'.green.bold)
   console.log(costo * 150);
 })

 cmd.parse(process.argv);